### ISSUE TITLE
Can't have A and AAAA records that point to the same hostname

### ISSUE THREAD

**Issue by worr** [cohoe/starrs-web#145]
ponyexpress.csh.rit.edu should point to 129.21.49.25 and 2620:8d:8000:e49:250:8bff:feec:b52e. It does not, and STARRS currently doesn't support this feature.

**Comment by agargiulo** [comment]
I don't know the steps you took to set it up, but limbo.csh.rit.edu points
to 129.21.49.36 and 2620:8d:8000:e49:209:6bff:fe49:8b88 and I set that up
in STARRS.

**Comment by cohoe** [comment]
STARRS does support this

**Comment by worr** [comment]
Ok, I didn't set up an address, which is why it wasn't working for me. Sorry for the issue.
