### ISSUE TITLE
Repetitive Expand All and Collapse All Not Working

### ISSUE THREAD

**Issue by eatnumber1** [cohoe/starrs-web#23]
Repeatedly clicking `Expand All` then `Collapse All` will not have the same behavior every time.

**Comment by cohoe** [comment]
These links are here for debugging purposes. Inclusion in actual release is not planned.

**Comment by dtyler** [comment]
I would suggest removing these sooner rather than later. There is already enough data such that expand all is a poor idea (crashes my chrome tab).

**Comment by cohoe** [comment]
This has been removed
