### ISSUE TITLE
Help System throws Fatal Error

### ISSUE THREAD

**Issue by eatnumber1** [cohoe/starrs-web#27]
`https://impulse.csh.rit.edu/reference/api/reference/help` throws the PHP error:

`Fatal error: Uncaught exception 'ObjectNotFoundException' with message 'Object not found!' in /users/u17/cohoe/.html_pages/impulse/application/libraries/core/ImpulseModel.php:28 Stack trace: #0 /users/u17/cohoe/.html_pages/impulse/application/models/API/api_documentation.php(31): ImpulseModel->_check_error(Object(CI_DB_postgre_result)) #1 /users/u17/cohoe/.html_pages/impulse/application/controllers/reference.php(61): Api_documentation->get_schema_documentation('reference') #2 /users/u17/cohoe/.html_pages/impulse/application/controllers/reference.php(41): Reference->_load_api_functions('reference') #3 [internal function]: Reference->api('reference', 'help') #4 /users/u17/cohoe/.html_pages/impulse/ci_system/core/CodeIgniter.php(339): call_user_func_array(Array, Array) #5 /users/u17/cohoe/.html_pages/impulse/index.php(201): require_once('/users/u17/coho...') #6 {main} thrown in /users/u17/cohoe/.html_pages/impulse/application/libraries/core/ImpulseModel.php on line 28`

**Comment by cohoe** [comment]
Initially got here due to a bad link. that was fixed, but exception handling was added anyway
