### ISSUE TITLE
Creating Firewall Rules Fails

### ISSUE THREAD

**Issue by eatnumber1** [cohoe/starrs-web#30]
Clicking `Create` on a machine's firewall rules page for an address produces the following error:

`Parse error: syntax error, unexpected T_VARIABLE, expecting ',' or ';' in /users/u17/cohoe/.html_pages/impulse/application/views/firewall/standalone_create.php on line 16`

On pages such as `https://impulse.csh.rit.edu/firewall/rules/view/129.21.50.103`

**Comment by cohoe** [comment]
Caused by an forgotten . in URL string concatenation. Cancel link also updated
