### ISSUE TITLE
quickstart creates DNS entries properly for hosts, manual creation does not

### ISSUE THREAD

**Issue by clockfort** [cohoe/starrs-web#35]
Quickstart creation of a machine sets up A/reverse PTR records properly; the manual method of systems-->create--->blahblah does not create DNS entries properly.
The workaround seems to be deleting the A records that a user owns and re-adding them manually.

Can you check the API call flow or something while trying these two separate test cases?

**Comment by cohoe** [comment]
This was first an issue with an exception getting overridden and not halting execution. Can you verify that this is still an issue with newly created records?

**Comment by cohoe** [comment]
No response from customer.

**Comment by clockfort** [comment]
ah, jesus, fine, testing now.
