### ISSUE TITLE
Pages have a very large fixed width

### ISSUE THREAD

**Issue by digitalcora** [cohoe/starrs-web#39]
The site design seems to be fixed at 1200px wide. For those with non-maximized browser windows or smaller resolutions (netbooks, tablets, etc.), this results in horizontal scrolling. If no content on the site actually _needs_ to be that wide, I'd recommend 960px as a "safe" fixed width. Of course, a fluid layout using min-width and max-width would be nicer, but one step at a time.

**Comment by cohoe** [comment]
The fixed size was due to the search results page. However I do want to shrink the page layout to fit within the safe zone (with fluidity).

**Comment by cohoe** [comment]
Not-an-issue as of 3d1856c7e4bc0306d5086e009e7205a1c79739e0
