### ISSUE TITLE
search is case sensitive

### ISSUE THREAD

**Issue by clockfort** [cohoe/starrs-web#40]
so searching 'games' does not retrieve 'Games'.

Expected behavior: case insensitive search

It might also be worthwhile to force some sort of case restrictions on hostnames for other reasons, since dns is case insensitive anyways

**Comment by cohoe** [comment]
done. search is now insensitive

**Comment by clockfort** [comment]
daaaayuuum. Fast issue close there, bro. Congrats, I'll bring you a project work weekend soda :-)
