### ISSUE TITLE
GNU/Hurd

### ISSUE THREAD

**Issue by agargiulo** [cohoe/starrs-web#43]
A PHP Error was encountered

Severity: Notice

Message: Undefined index: GNU/Hurd

Filename: libraries/Impulselib.php

Line Number: 81
https://impulse.csh.rit.edu/>

**Comment by cohoe** [comment]
php error fixed; need an image for it. Feel like making a 48x48 px image for it?

**Comment by cohoe** [comment]
Anthony should make a 48x48 image for it :)

**Comment by agargiulo** [comment]
http://csh.rit.edu/~agargiulo/hurd.gif
