### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by dtyler** [cohoe/starrs-web#46]
I went directly to the search page after logging in and was greeted by the following message across the top of my page. The rest of the page loaded properly .

A PHP Error was encountered

Severity: Notice

Message: session_start() [function.session-start]: ps_files_cleanup_dir: opendir(/var/lib/php5) failed: Permission denied (13)

Filename: core/ImpulseController.php

Line Number: 52

**Comment by cohoe** [comment]
Looks like this is a configuration thing on the web server (since it moved). Will look at what it takes to fix this.

**Comment by clockfort** [comment]
+1

**Comment by cohoe** [comment]
I have chown'd the directory to the www-data user. lets see what that does.
