### ISSUE TITLE
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png

### ISSUE THREAD

**Issue by clockfort** [cohoe/starrs-web#49]
Allow me to share a selection from apache's log files...
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png
File does not exist: /var/www/priv/impulse/media/images/sidebar/statistic.png

**Comment by cohoe** [comment]
lol, I forgot about that. fixed.
