### ISSUE TITLE
Not decoding URL

### ISSUE THREAD

**Issue by cohoe** [cohoe/starrs-web#58]
ERROR: invalid input syntax for type cidr: "129.21.50.0%2F24" LINE 1: SELECT \* FROM api.get_dhcp_subnet_options('129.21.50.0%2F24'... ^

https://impulse.csh.rit.edu/dhcp/options/view/subnet/129.21.50.0%252F24

From Canceling a subnet dhcp option creation

**Comment by benrr101** [comment]
It looks like it is being escaped twice. The %25 is for '%' and the 2F after that is for '/'. So ideally you want 129.21.50.0%2F24 => 129.21.50.0/24

**Comment by cohoe** [comment]
Not-an-issue as of 3d1856c7e4bc0306d5086e009e7205a1c79739e0
