### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by cohoe** [cohoe/starrs-web#96]
Fatal error: Uncaught exception 'ObjectNotFoundException' with message 'Object not found!' in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php:27 Stack trace: #0 /users/u17/cohoe/.html_pages/projects/impulse2/application/models/API/Network/api_network_get.php(114): ImpulseModel->_check_error(Object(CI_DB_postgre_result)) #1 /users/u17/cohoe/.html_pages/projects/impulse2/application/controllers/ip/subnetcontroller.php(191): Api_network_get->vlans('CSH-West') #2 [internal function]: Subnetcontroller->modify('50.116.14.176%2...') #3 /users/u17/cohoe/.html_pages/projects/impulse2/ci_system/core/CodeIgniter.php(359): call_user_func_array(Array, Array) #4 /users/u17/cohoe/.html_pages/projects/impulse2/index.php(202): require_once('/users/u17/coho...') #5 {main} thrown in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php on line 27

**Comment by agargiulo** [comment]
Fatal error: Uncaught exception 'ObjectNotFoundException' with message 'Object not found!' in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php:27 Stack trace: #0 /users/u17/cohoe/.html_pages/projects/impulse2/application/models/API/Systems/api_systems_get.php(208): ImpulseModel->_check_error(Object(CI_DB_postgre_result)) #1 /users/u17/cohoe/.html_pages/projects/impulse2/application/controllers/address.php(105): Api_systems_get->interfacesBySystem('burbclave') #2 [internal function]: Address->create('00%3A14%3Ac2%3A...') #3 /users/u17/cohoe/.html_pages/projects/impulse2/ci_system/core/CodeIgniter.php(359): call_user_func_array(Array, Array) #4 /users/u17/cohoe/.html_pages/projects/impulse2/index.php(202): require_once('/users/u17/coho...') #5 {main} thrown in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php on line 27

https://starrs.csh.rit.edu/address/create/00%3A14%3Ac2%3A40%3A3e%3Abe

**Comment by agargiulo** [comment]
Fatal error: Uncaught exception 'ObjectNotFoundException' with message 'Object not found!' in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php:27 Stack trace: #0 /users/u17/cohoe/.html_pages/projects/impulse2/application/models/API/Systems/api_systems_get.php(208): ImpulseModel->_check_error(Object(CI_DB_postgre_result)) #1 /users/u17/cohoe/.html_pages/projects/impulse2/application/controllers/address.php(105): Api_systems_get->interfacesBySystem('burbclave') #2 [internal function]: Address->create('00%3A50%3A8b%3A...') #3 /users/u17/cohoe/.html_pages/projects/impulse2/ci_system/core/CodeIgniter.php(359): call_user_func_array(Array, Array) #4 /users/u17/cohoe/.html_pages/projects/impulse2/index.php(202): require_once('/users/u17/coho...') #5 {main} thrown in /users/u17/cohoe/.html_pages/projects/impulse2/application/libraries/core/ImpulseModel.php on line 27

https://starrs.csh.rit.edu/address/create/00%3A50%3A8b%3Ae8%3A89%3A7a
